### ISSUE TITLE
Reading .torrent files from stdin

### ISSUE THREAD

**Issue by Teteros** [ngoldman/magnet-link#2]
May I suggest adding stdin read support?
Being able to read from pipes would work nicely with tools like [create-torrent](https://github.com/feross/create-torrent) which output to stdout.

**Comment by ungoldman** [comment]
Sounds good to me! @Teteros do you have experience reading from stdin? What do you think is the best way to implement that?

**Comment by Teteros** [comment]
@ngoldman Only as a user I'm afraid :(
No development background unfortunately so I can't say...

**Comment by elsehow** [comment]
you should be able to `process.stdin.pipe()`

see [stream-handbook](https://github.com/substack/stream-handbook)

[parse-torrent](https://www.npmjs.com/package/parse-torrent) may be useful, if you don't use it already

**Comment by ungoldman** [comment]
`magnet-link@^1.1.1` introduces pipe support. So you can do:

```
cat torrent.file | magnet-link
magnet-link < torrent.file
create-torrent . | magnet-link
```

:tada:
