### ISSUE TITLE
Include tracker and other parameters present in torrent file

### ISSUE THREAD

**Issue by aurimus** [ngoldman/magnet-link#3]
Hey, would be great to have those

**Comment by ungoldman** [comment]
Hi @aurimus, not sure what you mean. This module is specifically for getting a magnet link and nothing else. You may want to check out the read-torrent module.

**Comment by aurimus** [comment]
I think it maybe already does that, not sure, my error was somewhere else. The magnet link can contain other info, like trackers. I ended up using parse-torrent.
